#
# Copyright (c) 2020,2021 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sockshop-ingress
spec:
  rules:
  - host: ${SOCKSHOP_BACKEND:=coherence}.${SOCKSHOP_DOMAIN:=sockshop.helidon.io}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: front-end
            port:
              number: 80
  - host: jaeger.${SOCKSHOP_BACKEND:=coherence}.${SOCKSHOP_DOMAIN:=sockshop.helidon.io}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: jaeger-query
            port:
              number: 16686
  - host: api.${SOCKSHOP_BACKEND:=coherence}.${SOCKSHOP_DOMAIN:=sockshop.helidon.io}
    http:
      paths:
        - path: /carts
          pathType: ImplementationSpecific
          backend:
            service:
              name: carts
              port:
                number: 80
        - path: /catalogue
          pathType: ImplementationSpecific
          backend:
            service:
              name: catalogue
              port:
                number: 80
        - path: /orders
          pathType: ImplementationSpecific
          backend:
            service:
              name: orders
              port:
                number: 80
        - path: /paymentAuth
          pathType: ImplementationSpecific
          backend:
            service:
              name: payment-http
              port:
                number: 80
        - path: /shipping
          pathType: ImplementationSpecific
          backend:
            service:
              name: shipping-http
              port:
                number: 80
        - path: /login
          pathType: ImplementationSpecific
          backend:
            service:
              name: user
              port:
                number: 80
        - path: /register
          pathType: ImplementationSpecific
          backend:
            service:
              name: user
              port:
                number: 80
        - path: /customers
          pathType: ImplementationSpecific
          backend:
            service:
              name: user
              port:
                number: 80
        - path: /addresses
          pathType: ImplementationSpecific
          backend:
            service:
              name: user
              port:
                number: 80
        - path: /cards
          pathType: ImplementationSpecific
          backend:
            service:
              name: user
              port:
                number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$$2
  name: mp-ingress
spec:
  rules:
  - host: mp.${SOCKSHOP_BACKEND:=coherence}.${SOCKSHOP_DOMAIN:=sockshop.helidon.io}
    http:
      paths:
        - path: /swagger(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: swagger
              port:
                number: 80
        - path: /carts(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: carts
              port:
                number: 80
        - path: /catalogue(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: catalogue
              port:
                number: 80
        - path: /orders(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: orders
              port:
                number: 80
        - path: /payments(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: payment-http
              port:
                number: 80
        - path: /shipping(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: shipping-http
              port:
                number: 80
        - path: /users(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: user
              port:
                number: 80
